DATASET:
    MODE_CNN: 'sequential'
MODEL:
    NAME: 'DenseNet121'
    CRITERION: 'BCEWithLogitsLoss'
    OPTIMIZER: 'Adam'

TRAIN:
    EPOCHS: 100
    BATCH_SIZE: 64
    INITIAL_LR: 0.0005

    
REPORT:
    TENSORBOARD_PATH: './tensorboard/cnn'
    WEIGHTS_SAVE_PATH: './checkpoints/cnn'
    WEIGHTS_LOAD_PATH: './checkpoints/cnn/200617_190314_DenseNet121_LR0.0005_BS64_BCELoss/031.pth'

    
    

